app: frontend
env: staging
namespace: default
deploy:
  branch: main
  event: push
chart:
  repository: https://chart.onechart.dev
  name: onechart
  version: 0.32.0
values:
  replicas: 2
  image:
    repository: myapp
    tag:  "{{ .GITHUB_SHA }}"
