---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: myapp
  namespace: gimlet-demo-staging
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: onechart
      app.kubernetes.io/instance: myapp
