---
apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: gimlet-demo-staging
  labels:
    helm.sh/chart: onechart-0.31.0
    app.kubernetes.io/name: onechart
    app.kubernetes.io/instance: myapp
    app.kubernetes.io/managed-by: Helm
  annotations:
    gimlet.io/git-repository: laszlocph/gimletd-test-repo
    gimlet.io/git-sha: 071431009c8e9d6293d16f58b4d1a7176eac953b
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    
  selector:
    app.kubernetes.io/name: onechart
    app.kubernetes.io/instance: myapp
